# version: '3'

# services:
#   selenium:               # selenium container
#     image: selenium/standalone-chrome:latest # docker hubのselenium公式イメージ
#     shm_size: 2gb         # ホストとメモリを共有するために設定
#     ports:
#       - 4444:4444         # selenium sever port
#       - 7900:7900         # 実行中のChromeを確認するVNC用port
  
#   python:                 # python container
#     build: ./py_context   # python3のbuild contextを指定
#     volumes: 
#       - ./work:/work      # ローカルの"./work"とコンテナの"/work"をバインド
#     tty: true             # ターミナル入力を受け付ける
#     depends_on:           # seleniumコンテナの後で起動させるように指定
#       - selenium
#     ports:
#       - 8080:8080         # pythonのflaskサーバーのport

version: "3"

services:
  chrome:
    build: .
    restart: unless-stopped
    ports:
      - 4444:4444
      - 15900:5900
      - 8080:8080
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
      - .:/app
    environment:
      - SCREEN_WIDTH=1600
      - SCREEN_HEIGHT=900